### ISSUE TITLE
Ros2 installation issue 

### ISSUE THREAD

**Issue by kethan637** [Interbotix/interbotix_ros_manipulators#192]
### Question

curl is already the newest version (7.81.0-1ubuntu1.16).
git is already the newest version (1:2.34.1-1ubuntu1.10).
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
Requirement already satisfied: transforms3d in /usr/local/lib/python3.10/dist-packages (0.4.1)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Reading package lists...
Building dependency tree...
Reading state information...
python3-pip is already the newest version (22.0.2+dfsg-1ubuntu0.4).
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: modern_robotics in ./.local/lib/python3.10/site-packages (1.1.1)
Requirement already satisfied: numpy in /usr/lib/python3/dist-packages (from modern_robotics) (1.21.5)
ros-humble-desktop-full is already installed!
Traceback (most recent call last):
  File "/opt/ros/humble/bin/ros2", line 33, in <module>
    sys.exit(load_entry_point('ros2cli==0.18.9', 'console_scripts', 'ros2')())
  File "/opt/ros/humble/lib/python3.10/site-packages/ros2cli/cli.py", line 91, in main
    rc = extension.main(parser=parser, args=args)
  File "/opt/ros/humble/lib/python3.10/site-packages/ros2pkg/command/pkg.py", line 37, in main
    return extension.main(args=args)
  File "/opt/ros/humble/lib/python3.10/site-packages/ros2pkg/verb/list.py", line 24, in main
    print(pkg_name)
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
Apriltag ROS Wrapper already installed!
Traceback (most recent call last):
  File "/opt/ros/humble/bin/ros2", line 33, in <module>
    sys.exit(load_entry_point('ros2cli==0.18.9', 'console_scripts', 'ros2')())
  File "/opt/ros/humble/lib/python3.10/site-packages/ros2cli/cli.py", line 91, in main
    rc = extension.main(parser=parser, args=args)
  File "/opt/ros/humble/lib/python3.10/site-packages/ros2pkg/command/pkg.py", line 37, in main
    return extension.main(args=args)
  File "/opt/ros/humble/lib/python3.10/site-packages/ros2pkg/verb/list.py", line 24, in main
    print(pkg_name)
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
Interbotix Arm ROS 2 packages already installed!
Environment variables already set!
Installation complete, took 36 seconds in total.
NOTE: Remember to reboot the computer before using the robot!
bucky@bucky:~$ ros2 launch interbotix_xsarm_descriptions xsarm_description.launch.py robot_model:=wx200 use_joint_pub_gui:=true
Package 'interbotix_xsarm_descriptions' not found: "package 'interbotix_xsarm_descriptions' not found, searching: ['/home/bucky/apriltag_ws/install/apriltag_ros', '/opt/ros/humble']"

i am getting this issue when i am instaling the ros2 i tried many time same issue comin then i uninstalled and and install then also same issue not able to launch the install the ros2 humble please help us

### Robot Model

wx200

### Operating System

Ubuntu 22.04

### ROS Version

ROS 2 Humble

**Comment by kethan637** [comment]
can you reply it to the issue very urgent
