### ISSUE TITLE
[Question]: VX300 cannot be displayed correctly in RViz

### ISSUE THREAD

**Issue by eewind** [Interbotix/interbotix_ros_manipulators#230]
### Question

I am testing a vx300 robotic arm with Ubuntu 20.04 system installed with ROS/ xsarm_amd64_install.sh -d noetic， Connect the vx300 to the computer and use DYNAMIXEL Wizard 2.0 to recognize and control all motors. After closing DYNAMIXEL Wizard 2.0. Running roscore is normal. Running roslaunch interbotix_xsarm_descriptions xsarm_description. Launch robot_madel:=vx300 use_joint_pub_gui:=true. RViz can be opened, but the complete robotic arm cannot be displayed. The interface prompts: 'The class required for this panel,' interbotix_xs_rviz/interbotix Control Panel ', could not be loaded.
Error:
Could not find library corresponding to plugin interbotix_xs_rviz/Interbotix Control Panel. Make sure the plugin description XML file has the correct name of the library and that the library actually exists.
```
(base) lb@lb:~/Documents$ ls /dev | grep ttyDXL
ttyDXL
```
```
(base) lb@lb:~/Documents$ roslaunch interbotix_xsarm_descriptions xsarm_description.launch robot_model:=vx300 use_joint_pub_gui:=true
... logging to /home/lb/.ros/log/10906f72-8ecb-11ef-8013-5746d385a7dd/roslaunch-lb-5586.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://192.168.1.114:40555/

SUMMARY
========

PARAMETERS
 * /rosdistro: noetic
 * /rosversion: 1.17.0
 * /vx300/robot_description: <?xml version="1....

NODES
  /vx300/
    joint_state_publisher_gui (joint_state_publisher_gui/joint_state_publisher_gui)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    rviz (rviz/rviz)

ROS_MASTER_URI=http://localhost:11311

process[vx300/joint_state_publisher_gui-1]: started with pid [5602]
process[vx300/robot_state_publisher-2]: started with pid [5603]
process[vx300/rviz-3]: started with pid [5604]
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/joint_state_publisher_gui/joint_state_publisher_gui", line 39, in <module>
    import rospy
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/__init__.py", line 49, in <module>
    from .client import spin, myargv, init_node, \
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/client.py", line 52, in <module>
    import roslib
  File "/opt/ros/noetic/lib/python3/dist-packages/roslib/__init__.py", line 50, in <module>
    from roslib.launcher import load_manifest  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/ros/noetic/lib/python3/dist-packages/roslib/launcher.py", line 42, in <module>
    import rospkg
ModuleNotFoundError: No module named 'rospkg'
[vx300/joint_state_publisher_gui-1] process has died [pid 5602, exit code 1, cmd /opt/ros/noetic/lib/joint_state_publisher_gui/joint_state_publisher_gui __name:=joint_state_publisher_gui __log:=/home/lb/.ros/log/10906f72-8ecb-11ef-8013-5746d385a7dd/vx300-joint_state_publisher_gui-1.log].
log file: /home/lb/.ros/log/10906f72-8ecb-11ef-8013-5746d385a7dd/vx300-joint_state_publisher_gui-1*.log
[ERROR] [1729419785.159821680]: PluginlibFactory: The plugin for class 'interbotix_xs_rviz/Interbotix Control Panel' failed to load.  Error: Could not find library corresponding to plugin interbotix_xs_rviz/Interbotix Control Panel. Make sure the plugin description XML file has the correct name of the library and that the library actually exists.
```

### Robot Model

vx300

### Operating System

Ubuntu 20.04

### ROS Version

ROS 1 Noetic

**Comment by lukeschmitt-tr** [comment]
It looks like you are using a virtual environment. ROS does not play well with those - please deactivate your virtual environment before using ROS or our Python-ROS API.
