### ISSUE TITLE
[Question]: Packages like 'interbotix_xsarm_descriptions' are not found

### ISSUE THREAD

**Issue by ShounakDas101** [Interbotix/interbotix_ros_manipulators#85]
### Question

Question

I have followed all steps in "ROS2 Interface" documents multiple times but Packages like 'interbotix_xsarm_descriptions' are not found. I am unable to Apriltag ROS and interbotix_ws properly. I have tried updating rosdep. 

### Robot Model

rx150

### Operating System

Ubuntu 22.04

### ROS Version

ROS 2 Humble

### Additional Info
```shell
shounak@shounak-Dell-G15-5515:~$ ./xsarm_amd64_install.sh -d humble
Chosen Version: ROS2 humble
Install the Interbotix Perception packages? This will include the RealSense and AprilTag packages as dependencies.
> yes
Install the MATLAB-ROS API?
> yes
INSTALLATION SUMMARY:
	ROS Distribution:           ROS 2 humble
	Install Perception Modules: true
	Install MATLAB Modules:     true
	Installation path:          /home/shounak/interbotix_ws

Is this correct?
> yes



**********************************************

            Starting installation!            
   This process may take around 15 Minutes!   

**********************************************



Get:1 file:/var/cudnn-local-repo-ubuntu2004-8.8.1.3  InRelease [1,572 B]
Get:1 file:/var/cudnn-local-repo-ubuntu2004-8.8.1.3  InRelease [1,572 B]
Hit:2 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  InRelease
Hit:3 https://dl.google.com/linux/chrome/deb stable InRelease                                                                                                                                             
Hit:4 http://security.ubuntu.com/ubuntu jammy-security InRelease                                                                                                                                          
Hit:5 http://repo.ros2.org/ubuntu/main jammy InRelease                                                                                              
Hit:6 http://in.archive.ubuntu.com/ubuntu jammy InRelease           
Hit:7 http://packages.ros.org/ros2/ubuntu jammy InRelease
Hit:8 http://in.archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:9 http://in.archive.ubuntu.com/ubuntu jammy-backports InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
W: http://repo.ros2.org/ubuntu/main/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
Get more security updates through Ubuntu Pro with 'esm-apps' enabled:
  libjs-jquery-ui libopenexr-dev libopenexr25 libswscale-dev libavcodec58
  libavutil56 libswscale5 libavutil-dev libswresample3 libavformat58
  libavformat-dev libavcodec-dev libswresample-dev
Learn more about Ubuntu Pro at https://ubuntu.com/pro
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
curl is already the newest version (7.81.0-1ubuntu1.10).
openssh-server is already the newest version (1:8.9p1-3ubuntu0.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: transforms3d in /usr/local/lib/python3.10/dist-packages (0.4.1)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
python3-pip is already the newest version (22.0.2+dfsg-1ubuntu0.2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: modern_robotics in ./.local/lib/python3.10/site-packages (1.1.1)
Requirement already satisfied: numpy in /usr/lib/python3/dist-packages (from modern_robotics) (1.21.5)
ros-humble-desktop-full is already installed!
ROS_DISTRO was set to 'rolling' before. Please make sure that the environment does not mix paths from different distributions.
Installing Apriltag ROS Wrapper...
Cloning into 'apriltag_ros'...
remote: Enumerating objects: 920, done.
remote: Counting objects: 100% (337/337), done.
remote: Compressing objects: 100% (94/94), done.
remote: Total 920 (delta 274), reused 243 (delta 243), pack-reused 583
Receiving objects: 100% (920/920), 566.82 KiB | 1.16 MiB/s, done.
Resolving deltas: 100% (562/562), done.
#All required rosdeps installed successfully
Starting >>> apriltag_ros
--- stderr: apriltag_ros
Traceback (most recent call last):
  File "/home/shounak/.local/bin/cmake", line 5, in <module>
    from cmake import cmake
ModuleNotFoundError: No module named 'cmake'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_core/executor/__init__.py", line 91, in __call__
    rc = await self.task(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/colcon_core/task/__init__.py", line 93, in __call__
    return await task_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/colcon_ros/task/ament_cmake/build.py", line 59, in build
    rc = await extension.build(
  File "/usr/lib/python3/dist-packages/colcon_cmake/task/cmake/build.py", line 87, in build
    rc = await self._reconfigure(args, env)
  File "/usr/lib/python3/dist-packages/colcon_cmake/task/cmake/build.py", line 182, in _reconfigure
    buildfile = get_buildfile(cmake_cache)
  File "/usr/lib/python3/dist-packages/colcon_cmake/task/cmake/__init__.py", line 112, in get_buildfile
    if 'Ninja' in generator:
TypeError: argument of type 'NoneType' is not iterable
---
Failed   <<< apriltag_ros [0.07s, exited with code 1]

Summary: 0 packages finished [0.24s]
  1 package failed: apriltag_ros
  1 package had stderr output: apriltag_ros
argument of type 'NoneType' is not iterable
[ERROR] Failed to build Apriltag ROS Wrapper.
[ERROR] Interbotix Installation Failed!
```

**Comment by LSinterbotix** [comment]
> ```
>   File "/home/shounak/.local/bin/cmake", line 5, in <module>
>     from cmake import cmake
> ModuleNotFoundError: No module named 'cmake'
> ```

Looks like there's something wrong with your Python environment. Do you have the cmake Python module installed?

> ```
> ROS_DISTRO was set to 'rolling' before. Please make sure that the environment does not mix paths from different distributions.
> ```

It also looks like you're mixing distributions here. Try to keep a environment that only sources Humble if trying to install Humble.

**Comment by LSinterbotix** [comment]
Do you have any further questions on this? Otherwise, this issue will be closed.
